"""initial migration

Revision ID: 356256fe7549
Revises: 
Create Date: 2024-08-23 11:06:14.850403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356256fe7549'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('residence_country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('mobile_number', sa.String(length=13), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
